### ISSUE TITLE
Memory Leak - On Destroy

### ISSUE THREAD

**Issue by rickyv3** [mendix/ChartJS#100]
We've updated all of our charts to include the on destroy microflow. This seems to have reduced the number of charts objects significantly. However, we have a page that displays charts for a specific entity listening to a list view. We create 3 charts on every click which could result in many charts being rendered during that one page visit. The onDestroy function on occurs when you navigate from the page, and when it does only the 3 charts being displayed are destroyed leaving up to hundreds of charts in memory for the entire session. Is there anything that can be done to fix this?

**Comment by JelteMX** [comment]
There is not a lot that can be done. If this issue remains, please contact Support. I did do some performance upgrades in [4.0.0](https://github.com/mendix/ChartJS/releases/tag/v4.0.0). I am closing this issue
