### ISSUE TITLE
MX 7.4 issue with conditional visibility

### ISSUE THREAD

**Issue by JelteMX** [mendix/ChartJS#103]
Comment from #102 from @recktenwaldfabian

---
The problem that I encounter is, that the widget is initialized and directly uninitialized again (only happens in 7.4, probably due to refresh+conditional visibility).
I don’t have a small test project for this yet.

What happens: in a mx.data callback in PieChart.js:111
html.set(this._numberNode, content !== null ? content.toString() : "");

this._numberNode is undefined (probably because the widget is already _destroyed).

The fix would consist of checking if this._destroyed===true before calling _processData.

Can you suggest on how to proceed with this? I’m already spending too much time looking for platform issues and setting up test projects…

**Comment by JelteMX** [comment]
Makes sense, I'll see if we can fix that

**Comment by JelteMX** [comment]
I will also test it in a test-project here

**Comment by recktenwaldfabian** [comment]
I just added this to Core.js and replace usage of _processData with _processDataChecked
```javascript
        // assert that widget is not already destroyed before processing data
        _processDataChecked: function() {
          if ( this._destroyed ) {
            logger.debug(this.id + " is already destroyed");
          } else {
            this._processData();
          }
        },
```

**Comment by JelteMX** [comment]
Got it, came up with something similar. Can you test [this version](https://github.com/mendix/ChartJS/raw/fix_mx_7/test/widgets/ChartJS.mpk) for me?

**Comment by recktenwaldfabian** [comment]
I can confirm that this is fixing my issue, but:

this._destroyed is set in _WidgetBase.js

I would think twice before setting that yourself.

**Comment by JelteMX** [comment]
You're right, let's not do that :-). Thanks! I'll update the code and create a new release
