### ISSUE TITLE
ChartJS Component much slower on Mendix 7.8.0 vs 7.7.1

### ISSUE THREAD

**Issue by glagron** [mendix/ChartJS#107]
Hi,

I have just upgraded my Mendix application from 7.7.1 to 7.8.0, and the (unchanged) ChartJS charts run much slower now, specifically rendering in ~10s on 7.8.0 vs ~2s on 7.7.1.

I updated Widgets; I even downloaded the ChartJS 7.8 and overrode it, to no avail.

There is a stark difference in performance. Is it a known issue? Is there a pending 7.8.x patch?

Thanks,

Guislain

**Comment by JelteMX** [comment]
As far as I know there shouldn't be any difference between the two Mendix versions, so this might be an R&D thing. I'll see if I can find the problem. As this widget is Platform supported, I also suggest creating a ticket with Support. Please reference this Github issue as well

**Comment by JelteMX** [comment]
The new version [4.0.0](https://github.com/mendix/ChartJS/releases/tag/v4.0.0) should have better performance, other than that, there is not much I can do. I am closing this issue
