### ISSUE TITLE
donut charts don't display

### ISSUE THREAD

**Issue by unpredicted** [mendix/ChartJS#11]
The donut chart doesn't display. Changing configuration settings didn't work to get any different result.

**Comment by Rvthof** [comment]
Can you try the newest version? There's been a few updates that might've helped.
Also, try clearing your cache if you've used an older version of the widget before.

**Comment by JelteMX** [comment]
Fixed in [v3.0.0](https://github.com/mendix/ChartJS/releases/tag/v3.0.0) release
