### ISSUE TITLE
Doughnut chart: Chart not refreshed after deselect a value in the legend

### ISSUE THREAD

**Issue by melvingrootenboers** [mendix/ChartJS#34]
The doughnut chart is not refreshed after deselecting a value in the legend.

In this example "Q1 sales target" is not selected, but still shown in the chart.
![image](https://cloud.githubusercontent.com/assets/10810429/6151008/3242ec2a-b213-11e4-95ec-896d1b9c9fcf.png)

**Comment by KermitPPI** [comment]
I noticed the same thing, I think this may be a problem with the chartjs library and not the widget itself.

**Comment by JelteMX** [comment]
Fixed in [v3.0.0](https://github.com/mendix/ChartJS/releases/tag/v3.0.0) release
