### ISSUE TITLE
All charts: Chart not shown in collapsed groupbox

### ISSUE THREAD

**Issue by melvingrootenboers** [mendix/ChartJS#35]
Chart not shown in Group box, when property "Collapsible" of Group box is set to "Yes (start collapsed)"

![image](https://cloud.githubusercontent.com/assets/10810429/6209708/0618955a-b5c9-11e4-89bb-d36594ebc22d.png)

**Comment by RoelandSalij** [comment]
This is an issue in Mx version 5.13 and earlier and will. Resize() isn't called when container element dimensions change. Will be fixed in 5.14, presumably .
