### ISSUE TITLE
Radar charts always filled

### ISSUE THREAD

**Issue by KermitPPI** [mendix/ChartJS#41]
Greetings,

I'm trying to use the datasetFill option for radar charts and set it to no filling; however, when I set the  datasetFill option to no, the chart is always filled.  This option works for line charts but not for radar charts.  Is this an issue with the widget or does it have anything to do with chartjs?  Thank you for your help.

**Comment by KermitPPI** [comment]
Hello, I actually just figured out that there was a bug with the ChartJS library, it has been fixed here https://github.com/nnnick/Chart.js/pull/1127/files , if you update the charts.js file in the widget with the three lines of code below, the datasetFill option will work. @GREdens 

 ctx.fillStyle = dataset.fillColor;
if(this.options.datasetFill)
{
     ctx.fill();
}

**Comment by JelteMX** [comment]
Fixed in [v3.0.0](https://github.com/mendix/ChartJS/releases/tag/v3.0.0) release
