### ISSUE TITLE
Polar Charts not rendering at proper size

### ISSUE THREAD

**Issue by chadevansMX** [mendix/ChartJS#43]
In the testing project, the Polar Chart type is not rendering at a proper size on the canvas. The chart ends up looking very small, especially when comparing with pie and donut. The chart is not usable in its current form in a project.
![size issue](https://cloud.githubusercontent.com/assets/8656111/7773703/39a465de-0074-11e5-92ba-79b395bdabb1.png)

**Comment by KermitPPI** [comment]
Try making the polar chart unresponsive and change the width and the height.  That seemed to work for me.
