### ISSUE TITLE
Line Chart w/multiple data sets - tooltip does not align with cursor.

### ISSUE THREAD

**Issue by rickyv3** [mendix/ChartJS#49]
When more than 1 data set exists (and thus multiple lines), the tooltip that is rendered on the chart canvas does not align with the user's mouse / cursor. It is typically a 2 points to the left of where the user would like the tooltip to be. See attached image for more details.

Please not that the tooltip displays correctly when there is only 1 data set (or the other data sets have been de-selected).

Thank you!

![chartjs_cursor](https://cloud.githubusercontent.com/assets/13573078/10377301/1ab53088-6dc8-11e5-874d-747391f4a62c.png)

**Comment by JelteMX** [comment]
Fixed in [v3.0.0](https://github.com/mendix/ChartJS/releases/tag/v3.0.0) release
