### ISSUE TITLE
Can't see all options at my resolution

### ISSUE THREAD

**Issue by RSomers-Timeseries** [mendix/ChartJS#50]
Dear ChartJs devteam,

I seem to be missing the "Maintain aspect ratio"  option on my BarChart settings due to my resolution. Is it possible to make the screen scroll when dealing with different resolutions?

![capture](https://cloud.githubusercontent.com/assets/15948831/11312052/ecf4e3b8-8fd3-11e5-986e-b3ed5ea7bb3b.PNG)

Many thanks,

R. Somers

**Comment by JelteMX** [comment]
Could you please file a ticket @ Mendix support? This is not an issue with the widget itself, but with the Modeler. This is handled by the Modeler-team

**Comment by RSomers-Timeseries** [comment]
Seems fair, will do. Thanks
