### ISSUE TITLE
Issues with v3.1.0

### ISSUE THREAD

**Issue by David-Sanders** [mendix/ChartJS#56]
Just downloaded this.  Issues encountered:
1. Cannot get built-in legend to display (above chart).  It seems to ignore new property
2. Chart sometimes only half draws and I need to refresh page to get it to load properly.  This was with a pie chart (which was the second chart on the same form.  The other was a stacked barchart)
3. With the legend at the bottom displayed, the label is justified left overlapping the color block

**Comment by JelteMX** [comment]
Issue 1: Should work. Can you let me know what version of the modeler you are using and which browser?
Issue 2: I have succesfully reproduced, seems to have problems with animating & multiple widgets. This is an issue with the library, trying to find a workaround.
Issue 3: This has to do with styling. Will see what I can do about it

**Comment by David-Sanders** [comment]
Hi Jelte

I have tested in Modeler versions 6.1.0 and 5.20.0 and my primary browser is Firefox (43.0.4)

Issue 1. Testing further, the display of the top legend seems to be affected by the settings of all the charts on a page, rather than just the one being configured.  The setting in the last chart on the page seems to affect all of them.

Issue 2. Understood.  This was not an issue with the earlier version of the widget.

Issue 3. Agreed, but I could not find a class to be able to affect this.  Similarly, there doesn’t seem to be a class to be able to affect the font-style of the top legend or the left and bottom axis labels.

**Comment by JelteMX** [comment]
Hi David.

All issues have been resolved and are adressed in the new release: https://github.com/mendix/ChartJS/releases/tag/v3.1.1
