### ISSUE TITLE
Charts don't always complete rendering

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/ChartJS#57]
Sometimes when loading the Charts, the charts don't completely render, causing the following:

![image](https://cloud.githubusercontent.com/assets/2244753/12386778/1920a59a-bdc8-11e5-9684-e68aead1d9c0.png)

Disabling / enabling a dataset in the legend solves the issue. I use the latest version (3.1)

**Comment by JelteMX** [comment]
Are you using [v3.1.1](https://github.com/mendix/ChartJS/releases/tag/v3.1.1)? This solves an issue with rendering multiple charts. See explanation here: https://mxforum.mendix.com/questions/9390/ChartJS-updates

**Comment by Mcpoowl** [comment]
Wow, I thought I did... Apparently I did not. v3.1.1. and the use of the Responsive Animation setting solves this.
