### ISSUE TITLE
Legend font doesn't work?

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/ChartJS#58]
I've tried many different fonts for the legend, but they all seem to default to Helvetica Neue.
Is there a list of compatible fonts? I even tried Comic Sans MS, luckily that didn't work either :-)

Tried so far:
Verdana
Arial
Times New Roman
Roboto
Comic Sans MS

None of these seem to change the font in the legend.

**Comment by JelteMX** [comment]
I will check this later this week. Seemed to work for me.

**Comment by Mcpoowl** [comment]
Let me know if you need any more information!

**Comment by JelteMX** [comment]
The same I asked in #57, do you still have this problem when you install v3.1.1?

**Comment by Mcpoowl** [comment]
I'll just close this issue.... ;)

**Comment by JelteMX** [comment]
Haha, no problem ;-)
