### ISSUE TITLE
Scaling of label on y-axis when using decimals

### ISSUE THREAD

**Issue by ramsom** [mendix/ChartJS#61]
I am using the line chart to display decimal values. Everything works except the labels on the y-axis ([http://s14.postimg.org/45iapoc9d/Snippet.png](http://s14.postimg.org/45iapoc9d/Snippet.png)). the maximum number of decimal positions is 5 however the scale on the y-axis seems to include alot more. Any idea why?

Thanks in advance.

**Comment by ramsom** [comment]
tried adding the scaleLabel: "<%=value/10%>" but does not seem to have any result, see debug info below:

`{"contextObj":null,"datasets":[{"scaleLabel":"<%=value/10%>","label":"values","backgroundColor":"rgba(220,220,220,0.2)","borderColor":"rgba(220,220,220,0.5)","pointColor":"rgba(220,220,220,0.8)","pointBorderColor":"rgba(220,220,220,0.8)","pointHoverBackgroundColor":"rgba(220,220,220,0.75)","pointHoverBorderColor":"rgba(220,220,220,1)","data":[0.6643,0.45425,0.58569,0.43931,0.42672,0.72525,0.39372,0.22726,0.35708,0.22957,0.27658,0.59887,0.22491,0.4371,0.22125,0.69883,0.27378,0.70195,0.64294,0.57762,0.45721,0.5271,0.23895,0.45011,0.43622,0.72534,0.24624,0.32526,0.24353,0.3964,0.45706,0.47261,0.22154,0.45711,0.60606,0.45845,0.69264,0.68918,0.4317,0.29426,0.44826,0.72271,0.23905,0.29668,0.42264,0.69302,0.7406,0.27639,0.48588,0.45503,0.72872,0.4623,0.32052,0.24283,0.47802,0.45109,0.22341,0.46537,0.73607,0.43248,0.49917,0.48263,0.47537,0.52098,0.41672,0.73156,0.42078,0.22884,0.62218,0.46779,0.48347,0.70743,0.43707,0.45504,0.21793,0.23289,0.48097,0.53957,0.71103,0.41379,0.45274,0.53172,0.46726,0.23946,0.72871,0.2206,0.47352,0.28852,0.48035,0.5625,0.26552,0.45054,0.4192,0.72993,0.4633,0.3659,0.64941,0.26142,0.47383,0.42972,0.47024,0.52879,0.43003,0.31592,0.40757,0.34867,0.7258,0.73346,0.2654,0.65444,0.6308,0.23472,0.45207,0.43381,0.46185,0.45642,0.63917,0.7027,0.2234,0.59185,0.39008,0.74193,0.45739,0.44908,0.75391,0.43176,0.25748,0.46031,0.70905,0.24771,0.47099,0.56469,0.23194,0.45767,0.47352,0.39417,0.5859,0.71971,0.46343,0.21947,0.72772,0.47236,0.73155,0.21694,0.47729,0.34208,0.27404,0.23766,0.22338,0.45881,0.44809,0.56945,0.47258,0.22257,0.24462,0.25271,0.45863,0.49615,0.42728,0.41358,0.68443,0.46783,0.56644,0.46178,0.44063,0.21996,0.45271,0.44224,0.54231,0.21727,0.4837,0.47109,0.72047,0.73005,0.25705,0.46459,0.22361,0.501,0.75282,0.43567,0.23002,0.38745,0.36189,0.70665,0.46768,0.46589,0.76461,0.30276,0.22625,0.46506,0.674,0.4535,0.4679,0.22582,0.4545,0.60796,0.46018,0.3206,0.63213,0.46281,0.25736,0.26347,0.45997,0.30626,0.45205,0.36205,0.62813,0.65838,0.71933,0.41301,0.45547,0.46217,0.57134,0.24078,0.50261,0.22815,0.62243,0.45564,0.3271,0.23269,0.44053,0.22587,0.6175,0.68276,0.43819,0.22337,0.45746,0.47228,0.72468,0.44749,0.24863,0.22048,0.52071,0.43946,0.46735,0.26216,0.61273,0.37493,0.22294,0.43211,0.21706,0.42974,0.38954,0.22345,0.28868,0.23296,0.22827,0.74919,0.4697,0.45573,0.2329,0.4554,0.23405,0.46059,0.4675,0.7158,0.4666,0.55068,0.29338,0.74497,0.65824,0.27568,0.38208,0.45187,0.46051,0.27887,0.62094,0.6765,0.48408,0.4604,0.25018,0.31763,0.67901,0.30625,0.49875,0.44996,0.42073,0.50724,0.60124,0.29013,0.43083,0.45493,0.47959,0.21953,0.51736,0.23795,0.54413,0.44421],"fill":true,"tension":0.4}],"labels":["2016-01-12T20:30:00.000+01:00","2016-01-12T11:00:00.000+01:00","2016-02-09T21:45:00.000+01:00","2016-01-11T08:00:00.000+01:00","2016-01-12T23:30:00.000+01:00","2016-01-12T19:00:00.000+01:00","2016-01-12T23:45:00.000+01:00","2016-01-11T05:15:00.000+01:00","2016-01-11T00:00:00.000+01:00","2016-01-12T03:00:00.000+01:00","2016-01-12T01:15:00.000+01:00","2016-01-11T21:30:00.000+01:00","2016-02-09T04:45:00.000+01:00","2016-01-12T08:30:00.000+01:00","2016-01-12T03:45:00.000+01:00","2016-01-12T20:00:00.000+01:00","2016-01-11T06:15:00.000+01:00","2016-01-11T19:45:00.000+01:00","2016-02-09T20:45:00.000+01:00","2016-01-12T16:30:00.000+01:00","2016-01-12T09:15:00.000+01:00","2016-01-12T22:30:00.000+01:00","2016-01-12T05:30:00.000+01:00","2016-02-09T13:45:00.000+01:00","2016-02-09T11:00:00.000+01:00","2016-01-11T19:00:00.000+01:00","2016-02-09T05:45:00.000+01:00","2016-01-12T00:30:00.000+01:00","2016-02-09T02:15:00.000+01:00","2016-02-09T23:45:00.000+01:00","2016-01-12T13:30:00.000+01:00","2016-01-11T10:00:00.000+01:00","2016-01-11T03:15:00.000+01:00","2016-01-12T10:15:00.000+01:00","2016-01-12T21:30:00.000+01:00","2016-01-11T14:30:00.000+01:00","2016-02-09T17:30:00.000+01:00","2016-01-11T20:00:00.000+01:00","2016-02-09T10:15:00.000+01:00","2016-02-09T06:30:00.000+01:00","2016-02-09T12:45:00.000+01:00","2016-01-12T17:15:00.000+01:00","2016-01-11T02:00:00.000+01:00","2016-01-12T06:30:00.000+01:00","2016-01-11T23:30:00.000+01:00","2016-02-09T20:00:00.000+01:00","2016-01-11T18:15:00.000+01:00","2016-02-09T01:15:00.000+01:00","2016-01-11T15:45:00.000+01:00","2016-02-09T12:00:00.000+01:00","2016-02-09T18:15:00.000+01:00","2016-01-12T14:30:00.000+01:00","2016-02-09T00:30:00.000+01:00","2016-01-12T02:15:00.000+01:00","2016-01-11T13:30:00.000+01:00","2016-02-09T14:30:00.000+01:00","2016-02-09T04:00:00.000+01:00","2016-01-12T12:00:00.000+01:00","2016-01-12T18:15:00.000+01:00","2016-02-09T09:30:00.000+01:00","2016-01-12T15:45:00.000+01:00","2016-01-11T12:00:00.000+01:00","2016-02-09T15:45:00.000+01:00","2016-01-11T22:30:00.000+01:00","2016-01-12T07:30:00.000+01:00","2016-01-11T17:15:00.000+01:00","2016-02-09T07:45:00.000+01:00","2016-02-09T05:00:00.000+01:00","2016-01-11T16:45:00.000+01:00","2016-02-09T15:30:00.000+01:00","2016-01-12T15:30:00.000+01:00","2016-01-12T19:45:00.000+01:00","2016-01-12T08:15:00.000+01:00","2016-01-12T10:45:00.000+01:00","2016-01-11T04:30:00.000+01:00","2016-01-12T02:45:00.000+01:00","2016-01-11T12:30:00.000+01:00","2016-01-12T16:15:00.000+01:00","2016-01-12T19:30:00.000+01:00","2016-02-09T08:30:00.000+01:00","2016-01-12T23:15:00.000+01:00","2016-01-11T16:15:00.000+01:00","2016-01-12T15:00:00.000+01:00","2016-02-09T02:30:00.000+01:00","2016-01-12T18:45:00.000+01:00","2016-01-12T04:30:00.000+01:00","2016-01-11T15:30:00.000+01:00","2016-01-11T00:45:00.000+01:00","2016-01-11T13:00:00.000+01:00","2016-02-09T22:00:00.000+01:00","2016-01-12T01:30:00.000+01:00","2016-02-09T14:00:00.000+01:00","2016-02-09T08:45:00.000+01:00","2016-01-11T18:45:00.000+01:00","2016-01-12T12:30:00.000+01:00","2016-01-12T07:00:00.000+01:00","2016-01-12T20:45:00.000+01:00","2016-02-09T06:00:00.000+01:00","2016-01-11T13:45:00.000+01:00","2016-02-09T23:30:00.000+01:00","2016-01-11T23:00:00.000+01:00","2016-02-09T16:30:00.000+01:00","2016-02-09T10:45:00.000+01:00","2016-01-11T06:45:00.000+01:00","2016-02-09T07:30:00.000+01:00","2016-01-12T00:15:00.000+01:00","2016-02-09T17:45:00.000+01:00","2016-01-11T18:30:00.000+01:00","2016-02-09T01:30:00.000+01:00","2016-01-11T20:30:00.000+01:00","2016-02-09T21:00:00.000+01:00","2016-02-09T02:45:00.000+01:00","2016-02-09T13:00:00.000+01:00","2016-02-09T09:45:00.000+01:00","2016-01-12T09:30:00.000+01:00","2016-01-12T13:45:00.000+01:00","2016-01-11T20:45:00.000+01:00","2016-02-09T19:45:00.000+01:00","2016-02-09T03:45:00.000+01:00","2016-01-12T21:45:00.000+01:00","2016-01-11T07:15:00.000+01:00","2016-01-12T17:30:00.000+01:00","2016-01-12T10:30:00.000+01:00","2016-01-11T23:15:00.000+01:00","2016-01-11T17:30:00.000+01:00","2016-02-09T10:30:00.000+01:00","2016-01-11T06:00:00.000+01:00","2016-01-11T15:00:00.000+01:00","2016-01-11T19:30:00.000+01:00","2016-01-12T05:45:00.000+01:00","2016-01-11T09:45:00.000+01:00","2016-02-09T16:45:00.000+01:00","2016-02-09T03:00:00.000+01:00","2016-01-12T12:45:00.000+01:00","2016-01-11T11:45:00.000+01:00","2016-01-12T07:15:00.000+01:00","2016-01-11T21:45:00.000+01:00","2016-02-09T19:00:00.000+01:00","2016-01-11T09:00:00.000+01:00","2016-01-11T03:30:00.000+01:00","2016-02-09T18:30:00.000+01:00","2016-01-12T15:15:00.000+01:00","2016-01-12T18:30:00.000+01:00","2016-01-11T04:15:00.000+01:00","2016-01-11T12:45:00.000+01:00","2016-02-09T00:15:00.000+01:00","2016-01-11T01:00:00.000+01:00","2016-01-12T02:30:00.000+01:00","2016-01-12T03:30:00.000+01:00","2016-01-12T11:45:00.000+01:00","2016-02-09T11:45:00.000+01:00","2016-01-11T16:30:00.000+01:00","2016-01-12T23:00:00.000+01:00","2016-01-12T04:45:00.000+01:00","2016-01-11T01:45:00.000+01:00","2016-01-11T01:30:00.000+01:00","2016-01-12T11:30:00.000+01:00","2016-01-11T22:45:00.000+01:00","2016-02-09T09:00:00.000+01:00","2016-02-09T08:15:00.000+01:00","2016-01-11T17:00:00.000+01:00","2016-01-12T12:15:00.000+01:00","2016-01-11T22:00:00.000+01:00","2016-02-09T15:15:00.000+01:00","2016-01-12T08:00:00.000+01:00","2016-01-12T04:15:00.000+01:00","2016-02-09T14:45:00.000+01:00","2016-02-09T11:30:00.000+01:00","2016-02-09T22:15:00.000+01:00","2016-01-11T03:45:00.000+01:00","2016-01-11T12:15:00.000+01:00","2016-01-11T09:30:00.000+01:00","2016-01-12T19:15:00.000+01:00","2016-02-09T18:00:00.000+01:00","2016-01-12T01:45:00.000+01:00","2016-01-12T14:45:00.000+01:00","2016-02-09T04:30:00.000+01:00","2016-02-09T16:15:00.000+01:00","2016-01-12T17:45:00.000+01:00","2016-02-09T10:00:00.000+01:00","2016-01-11T02:30:00.000+01:00","2016-02-09T07:15:00.000+01:00","2016-01-11T07:00:00.000+01:00","2016-02-09T19:30:00.000+01:00","2016-01-11T11:30:00.000+01:00","2016-01-11T10:45:00.000+01:00","2016-01-11T17:45:00.000+01:00","2016-02-09T00:45:00.000+01:00","2016-01-11T02:45:00.000+01:00","2016-01-11T15:15:00.000+01:00","2016-01-11T20:15:00.000+01:00","2016-02-09T23:15:00.000+01:00","2016-01-11T10:30:00.000+01:00","2016-02-09T03:30:00.000+01:00","2016-02-09T12:30:00.000+01:00","2016-02-09T17:00:00.000+01:00","2016-01-12T14:00:00.000+01:00","2016-01-12T06:45:00.000+01:00","2016-01-12T21:00:00.000+01:00","2016-01-11T14:00:00.000+01:00","2016-02-09T01:45:00.000+01:00","2016-01-12T06:00:00.000+01:00","2016-01-11T14:45:00.000+01:00","2016-01-12T00:45:00.000+01:00","2016-02-09T13:15:00.000+01:00","2016-02-09T07:00:00.000+01:00","2016-01-12T16:45:00.000+01:00","2016-02-09T20:30:00.000+01:00","2016-01-11T19:15:00.000+01:00","2016-01-11T07:30:00.000+01:00","2016-01-12T13:00:00.000+01:00","2016-01-12T09:45:00.000+01:00","2016-01-12T22:00:00.000+01:00","2016-01-11T05:45:00.000+01:00","2016-01-12T22:45:00.000+01:00","2016-01-12T05:00:00.000+01:00","2016-01-11T21:00:00.000+01:00","2016-01-12T11:15:00.000+01:00","2016-01-11T00:15:00.000+01:00","2016-02-09T05:15:00.000+01:00","2016-01-11T08:15:00.000+01:00","2016-01-12T03:15:00.000+01:00","2016-02-09T21:15:00.000+01:00","2016-01-12T20:15:00.000+01:00","2016-01-12T08:45:00.000+01:00","2016-01-11T05:00:00.000+01:00","2016-02-09T15:00:00.000+01:00","2016-02-09T23:00:00.000+01:00","2016-02-09T18:45:00.000+01:00","2016-01-11T08:45:00.000+01:00","2016-01-12T02:00:00.000+01:00","2016-01-12T04:00:00.000+01:00","2016-02-09T22:30:00.000+01:00","2016-02-09T11:15:00.000+01:00","2016-01-11T09:15:00.000+01:00","2016-01-11T01:15:00.000+01:00","2016-01-11T21:15:00.000+01:00","2016-02-09T00:00:00.000+01:00","2016-02-09T04:15:00.000+01:00","2016-01-12T07:45:00.000+01:00","2016-01-11T04:00:00.000+01:00","2016-01-11T07:45:00.000+01:00","2016-01-11T23:45:00.000+01:00","2016-01-11T03:00:00.000+01:00","2016-02-09T01:00:00.000+01:00","2016-01-11T05:30:00.000+01:00","2016-02-09T03:15:00.000+01:00","2016-01-11T18:00:00.000+01:00","2016-01-11T10:15:00.000+01:00","2016-02-09T12:15:00.000+01:00","2016-01-12T05:15:00.000+01:00","2016-01-12T13:15:00.000+01:00","2016-01-11T02:15:00.000+01:00","2016-01-12T10:00:00.000+01:00","2016-01-11T11:00:00.000+01:00","2016-02-09T19:15:00.000+01:00","2016-01-11T11:15:00.000+01:00","2016-01-12T22:15:00.000+01:00","2016-01-11T06:30:00.000+01:00","2016-01-12T18:00:00.000+01:00","2016-02-09T17:15:00.000+01:00","2016-02-09T06:15:00.000+01:00","2016-01-12T00:00:00.000+01:00","2016-02-09T13:30:00.000+01:00","2016-01-12T14:15:00.000+01:00","2016-01-12T06:15:00.000+01:00","2016-01-12T21:15:00.000+01:00","2016-02-09T20:15:00.000+01:00","2016-02-09T16:00:00.000+01:00","2016-01-11T14:15:00.000+01:00","2016-02-09T02:00:00.000+01:00","2016-02-09T06:45:00.000+01:00","2016-01-12T17:00:00.000+01:00","2016-01-11T00:30:00.000+01:00","2016-02-09T22:45:00.000+01:00","2016-02-09T14:15:00.000+01:00","2016-02-09T08:00:00.000+01:00","2016-01-11T16:00:00.000+01:00","2016-02-09T21:30:00.000+01:00","2016-01-12T01:00:00.000+01:00","2016-02-09T09:15:00.000+01:00","2016-01-12T09:00:00.000+01:00","2016-01-11T13:15:00.000+01:00","2016-01-11T04:45:00.000+01:00","2016-01-12T16:00:00.000+01:00","2016-02-09T05:30:00.000+01:00","2016-01-11T22:15:00.000+01:00","2016-01-11T08:30:00.000+01:00"]}`

**Comment by ramsom** [comment]
got the advice of ChartJS to use:

yAxes:[{
                        ticks:{
                        callback:function(value){
                        return Number(value).toFixed(3);
                        }
                        }
                        }],

any idea on how to intergrate this into your code?

**Comment by JelteMX** [comment]
Can you point where this code should be included? It's a weird problem, might have to do with the ChartJS library

**Comment by ramsom** [comment]
think it is an option that needs to be added to the creation of the object but was hoping you could give me a hand. checl (https://github.com/nnnick/Chart.js/issues/2001#issuecomment-182750887) asked your question.

**Comment by Criccle** [comment]
By request of @ramsom I tried to implement the above fix and it works perfectly. I will create a pull request for this.

**Comment by ramsom** [comment]
cool, thx

**Comment by ramsom** [comment]
works for me too, thanks for the help... maybe Jelte can create a more generic solution.

**Comment by JelteMX** [comment]
@Criccle awesome, thanks! I'll review the code (generic solution, see if we can set the amount of decimals in the Modeler itself) and merge this :+1:
