### ISSUE TITLE
Chart incorrect datasets, doesn't render correctly when inside groupbox

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/ChartJS#69]
When a Chart ( we tested a BarChart, but I'd imagine it goes the same for all charts ) is surrounded by a groupbox, the chart has incorrect data. In the example below you see the following:
- A BarChart within a Groupbox, The same dataset is shown twice ('Gemiddelde Marktprijs' ).
- A BarChart without the Groupbox. Using the same source as the previous BarChart, this one renders correctly, showing two datasets.

![groupboxchart](https://cloud.githubusercontent.com/assets/2244753/14012104/e1fcc66a-f1a3-11e5-9ec2-e2af3a697d71.png)

//edit: It seems it has something to do with the fact that there are multiple barcharts on the page.... Will keep investigating and updating
//edit2: It doesn't matter how many charts we have on the page. Even with one chart, in a groupbox it doesn't work. When moving the chart out of the groupbox, it works fine.

//edit3: Although it's still a bug in my opinion, upgrading to 6.3.1. seems to have solved the issue.... Weird

//edit4: Although it doesn't occur as often as it used to in 6.3.1. it DOES happen.. A lot more random though..
//edit 5: After some testing, retrying, retrying and retrying. we came to the following conclusion in the case of multiple bar charts on the same page

Groupbox: The chart is rendered incorrectly about 1 out of 5 times
Without groupbox: The chart renders correctly every time

**Comment by JelteMX** [comment]
I'll see when I have time to debug this issue. Seems strange because the datasets don't change. Thanks for testing, will do the same in 6.3.1

**Comment by JelteMX** [comment]
Could you test [the latest version](https://github.com/mendix/ChartJS/raw/master/test/widgets/ChartJS.mpk) for me? I have updated the chartjs library, so it might resolve some inconsistencies. This next version of the widget (v3.5.0) will tackle some issues (also regarding animation and responsive heights etc)

**Comment by Criccle** [comment]
![image](https://cloud.githubusercontent.com/assets/10046210/14810938/c5bb0bfe-0b95-11e6-95ee-5baf80795b09.png)

Hi Jelte. I went back a bunch of revisions to test it in a similar environment as the original issue and the issue still remains.

**Comment by JelteMX** [comment]
As in, this issue has always been there? I haven't noticed that. We'll further investigate what is going wrong. Or we'll ask to provide a test-project, sent to community [at] mendix.com, as I have not yet been able to reproduce this issue

**Comment by JelteMX** [comment]
Due to inactivity, and the fact that I have rewritten the widget for version [4.0.0](https://github.com/mendix/ChartJS/releases/tag/v4.0.0), I am closing this issue
