### ISSUE TITLE
(Double) doughnut max/min Y value

### ISSUE THREAD

**Issue by joelvdgraaf** [mendix/ChartJS#7]
The both widgets doughnut and double doughnut has the properties 'Minimum value Y axis' and 'Maximum value Y axis'. For the both widgets there is an option X value and Y value for the single datapoint. 
Those properties are irrelevant.

**Comment by Rvthof** [comment]
Fixed in 1b92696c61c174e6bfdb8b6714f1e0b0058ee3c7
