### ISSUE TITLE
lineChart scaleBeginAtZero is configurable but not functinal

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/ChartJS#72]
scaleBeginAtZero can be set as an option in the modeler,
However is is not implement inside the line chart widget

**Comment by Andries-Smit** [comment]
This issue is not solved. Please try to add a bar charts without any data points, and it will look like. Or is this expected behavior?

![image](https://cloud.githubusercontent.com/assets/6724749/14628797/5e8ef538-0601-11e6-8c3f-d230f93425a2.png)

![image](https://cloud.githubusercontent.com/assets/6724749/14628802/6a8be6d4-0601-11e6-8cdf-8ae5411359ea.png)

**Comment by JelteMX** [comment]
This is expected behaviour I guess, but I do have a workaround for this.

**Comment by JelteMX** [comment]
Can you check [this version](https://github.com/mendix/ChartJS/raw/master/test/widgets/ChartJS.mpk) for me?

**Comment by Andries-Smit** [comment]
Thanks a lot; Tested, this will do the trick.
It also helps with the ugly scale numbering on the y ax between 0 and 1 if the the lowest value is 1
