### ISSUE TITLE
Render Pie Chart, on hover, shows historic context data

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/ChartJS#76]
When hovering above a pie chart, it switches to historic data.

![pie chart render issue](https://cloud.githubusercontent.com/assets/6724749/14667522/07e15e3a-06e0-11e6-8435-41771adebf85.gif)

The context is changed a view times, the hover some how shows data of a previous context.

**Comment by JelteMX** [comment]
Can you create a specific test-project for this where I can debug this? I haven't seen this bug anywhere so far. (I am on Slack as well today)

**Comment by Andries-Smit** [comment]
Even better, I have a pull request 77

**Comment by JelteMX** [comment]
Merged #77, closing this issue, as this is resolved. Next version of the widget also has ChartJS v2.0.2 included, which probably makes #75 obsolete.
