### ISSUE TITLE
On Click microflows for Pie and Doughnut charts

### ISSUE THREAD

**Issue by David-Sanders** [mendix/ChartJS#78]
Testing on 3.5.0.  On click seems to work with bar charts, but not with Pie and Doughnut charts. The on click dataset microflow always passes the same (the last created) dataset to the microflow, not the dataset that was clicked

**Comment by JelteMX** [comment]
Good find, thanks. I'll check what is going wrong. From what I know the Pie and Doughnut chart get a single series dataset. Will debug this a little further and see what I can fix.

**Comment by David-Sanders** [comment]
Hi Jelte

That seems to work properly now… thanks. David
