### ISSUE TITLE
Feature: graph colors

### ISSUE THREAD

**Issue by joelvdgraaf** [mendix/ChartJS#8]
Within 360 there are colors for each type of data. The colors are created based RGBA. At this moment I'm missing to set the alpha value because of the colors are in RGB. Is there a solution to set the alpha value? Or as a separate optional property.

**Comment by JelteMX** [comment]
I checked this and there is a solution to this. The Modeler states that you need to put in the Fill & Highlight Color as a Hex value, e.g. `#FF00FF`. But... this will also work with RGBA values. Instead of using a hex value, make it `rgb(34,34,34,0.5)` and that will work as well
