### ISSUE TITLE
Can not select Decimal attribute as Value

### ISSUE THREAD

**Issue by AgnesR83** [mendix/ChartJS#96]
Can not select Decimal attribute as Value.
I rather not use the deprecated Float for the Value.

**Comment by JelteMX** [comment]
In which widget is this? As far as I know we added Decimal to all the attribute Types where Float was in

**Comment by AgnesR83** [comment]
ChartJs DoughnutChart

**Comment by JelteMX** [comment]
Ah, I see we missed something. I'll update this later, to use Decimal as well. Thanks for reporting 👍
