### ISSUE TITLE
Doughnut chart error when empty

### ISSUE THREAD

**Issue by AgnesR83** [mendix/ChartJS#97]
When Doughnut chart has no data set items it will result in a error on the browser console and this will prevent the rest of my page from loading.

mendix.sys.Data.get: xpath, guid|guids and microflow arguments are undefined
(anonymous) @ mxui.js?636226036139502877:7206
error @ mxui.js?636226036139502877:7230
get @ mxui.js?636226036139502877:30932
(anonymous) @ DoughnutChart.js:73
(anonymous) @ mxui.js?636226036139502877:4640
(anonymous) @ Core.js:606
(anonymous) @ mxui.js?636226036139502877:4640

**Comment by JelteMX** [comment]
This issue is related to #89. Currently writing a fix to check whether or not a microflow returns objects

**Comment by JelteMX** [comment]
Fixed in [3.6.0](https://github.com/mendix/ChartJS/releases/tag/v3.6.0)
