### ISSUE TITLE
Y Axis label on line chart

### ISSUE THREAD

**Issue by rickyv3** [mendix/ChartJS#99]
Per most recent release (5/10/2017) we have a bug affecting they axis when there is no data in the line chart. Mendix v6.10.3.

![yaxisbug](https://cloud.githubusercontent.com/assets/13573078/25963870/7a7e629c-3648-11e7-87ab-0d1095473e9f.png)

**Comment by JelteMX** [comment]
I have released [4.0.0](https://github.com/mendix/ChartJS/releases/tag/v4.0.0) which has a lot of updates regarding the ChartJS library. I am closing this issue, as it is related to the library. If the issue persists with the new version, please contact us again.
